version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - bdnet

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - bdnet

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    networks:
      - bdnet
    volumes:
      - ./src:/app
    command: ["/bin/sh","-c","sleep 5 && tail -f /dev/null"]

  streamer:
    build: .
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - UPSTOX_ACCESS_TOKEN=${UPSTOX_ACCESS_TOKEN}
    depends_on:
      - kafka
    networks:
      - bdnet
    working_dir: /app/src/Big Data Project
    command: ["python", "data_streamer.py"]

  plotter:
    build: .
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - bdnet
    working_dir: /app/src/Big Data Project
    ports:
      - "8050:8050"
    command: ["python", "data_plotter.py"]

networks:
  bdnet:
    driver: bridge
